[project]
authors = [{name = "Troy Smith", email = "Troy.Smith@uga.edu"}]
dependencies = []
name = "C5O-Kinetics"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
c5o_kinetics = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
ipykernel = ">=6.30.1,<7"
rdkit = ">=2025.3.5,<2026"
py3dmol = ">=2.5.2,<3"
click = ">=8.2.1,<9"
numpy = ">=2.3.2,<3"
